var doxygen = require('doxygen');

var userOptions = {
	PROJECT_NAME: '"Memory Project"',
	SHOW_FILES: "YES",
	OPTIMIZE_OUTPUT_JAVA: "YES",
	EXTRACT_ALL: "YES",
	EXTRACT_PRIVATE: "YES",
	EXTRACT_PACKAGE: "YES",
	EXTRACT_STATIC: "YES",
	EXTRACT_LOCAL_CLASSES: "YES",
	EXTRACT_LOCAL_METHODS: "YES",
	EXTRACT_ANON_NSPACES: "YES",
	SUBGROUPING: "YES",
	SOURCE_BROWSER: "YES",
	OUTPUT_DIRECTORY: "doc",
	INPUT: "./MemoryProject",
	EXCLUDE_PATTERNS: ["*/obj/*"],
	RECURSIVE: "YES",
	GENERATE_LATEX: "NO",
	INLINE_SOURCES: "YES",
	GENERATE_TREEVIEW: "YES",
	UML_LOOK: "YES",
	MULTILINE_CPP_IS_BRIEF: "YES",
	HTML_TIMESTAMP: "YES",
	USE_MATHJAX: "YES",
	USE_MDFILE_AS_MAINPAGE: "./README.md",
	HTML_DYNAMIC_SECTIONS: "YES",
	HTML_COLORSTYLE_HUE: 29,
	HTML_COLORSTYLE_SAT: 255,
	HTML_COLORSTYLE_GAMMA: 240,
	HAVE_DOT: "YES",
	DOT_IMAGE_FORMAT: "svg",
	INTERACTIVE_SVG: "YES",
	DOT_TRANSPARENT: "YES",
	CALL_GRAPH: "YES",
	CALLER_GRAPH: "YES"
};


doxygen.downloadVersion().then(function(data) {
  doxygen.createConfig(userOptions);
  doxygen.run();
});
